#! /usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.dirname(__FILE__) + '/../lib')

require "rackup"

rackup_file = File.realpath(File.dirname(__FILE__) + '/../config.ru')

ARGV << rackup_file
server = Rackup::Server.new
server.start
